apiVersion: v1
kind: Service
metadata:
  name: gateway-service2
spec:
  selector:
    app: gateway
  ports:
  - port: 5560
    targetPort: 80
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP